CREATE TABLE Users (
    UserId INT PRIMARY KEY IDENTITY,
    Username NVARCHAR(50) UNIQUE NOT NULL,
    Email NVARCHAR(100) UNIQUE NOT NULL,
    PasswordHash NVARCHAR(255) NOT NULL
);

CREATE TABLE Movies (
    MovieId INT PRIMARY KEY,
    Title NVARCHAR(255) NOT NULL,
    Genres NVARCHAR(255)
);

CREATE TABLE Ratings (
    RatingId INT PRIMARY KEY IDENTITY,
    UserId INT NOT NULL,
    MovieId INT NOT NULL,
    Rating FLOAT NOT NULL,
    CONSTRAINT FK_User FOREIGN KEY (UserId) REFERENCES Users(UserId),
    CONSTRAINT FK_Movie FOREIGN KEY (MovieId) REFERENCES Movies(MovieId)
);
